name: Compiler l'appli Android TV

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extraire le projet
        run: unzip -q tv-samples-leanback-afrocinex.zip

      - name: Installer Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Rendre gradlew exécutable
        run: chmod +x Leanback/gradlew

      - name: Compiler l'APK
        working-directory: Leanback
        run: ./gradlew assembleDebug

      - name: Publier l'APK compilé
        uses: actions/upload-artifact@v4
        with:
          name: afrocinex-tv-debug
          path: Leanback/app/build/outputs/apk/debug/*.apk
